version: '3'

services:
  db:
    image: mysql:8.0
    container_name: Shanks_DB
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    expose:
      - 3306
    volumes:
      - "./data/mysql:/var/lib/mysql"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -pパスワード
    ports:
      - "3306:3306"